import { test, expect } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'node:crypto';

test.use({ trace: 'off', video: 'off' });
test('artboard outline follows its draggable selection node', async ({ page, request }, info) => {
  test.skip(process.env.SUPABASE_URL !== 'http://127.0.0.1:54421', 'Local only');
  test.setTimeout(90000);
  const url = process.env.SUPABASE_URL!;
  const admin = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
  const auth = createClient(url, process.env.SUPABASE_ANON_KEY!, { auth: { persistSession: false } });
  const user = (await admin.auth.admin.getUserById('541006fa-d2a1-4305-be55-b6263c27a1e3')).data.user!;
  const link = (await admin.auth.admin.generateLink({ type: 'magiclink', email: user.email! })).data;
  const session = (await auth.auth.verifyOtp({ type: 'magiclink', token_hash: link.properties.hashed_token })).data.session!;
  const headers = { Authorization: `Bearer ${session.access_token}` };
  const server = 'http://127.0.0.1:3002';
  try {
    const created = await request.post(`${server}/api/projects`, { headers, data: { name: `Board drag sync ${Date.now()}` } });
    expect(created.ok()).toBe(true);
    const { project } = await created.json();
    const canvasId = project.primaryCanvas.id;
    const element = { id: 'test-board', type: 'rectangle', x: 100, y: 130, width: 260, height: 460, angle: 0, strokeColor: 'transparent', backgroundColor: '#ffffff', opacity: 0, fillStyle: 'solid', strokeWidth: 1, strokeStyle: 'solid', roughness: 0, groupIds: [], frameId: null, roundness: null, seed: 1, version: 1, versionNonce: 1, isDeleted: false, boundElements: null, updated: Date.now(), link: null, locked: false, customData: { kind: 'loomic-design', schemaVersion: 1, designId: randomUUID(), revision: 1, previewAssetObjectId: null, previewRevision: 0 } };
    expect((await request.put(`${server}/api/canvases/${canvasId}`, { headers, data: { content: { elements: [element], files: {}, appState: { scrollX: 0, scrollY: 0, zoom: { value: 1 } } } } })).ok()).toBe(true);
    await page.addInitScript(({ key, session }) => localStorage.setItem(key, JSON.stringify(session)), { key: `sb-${new URL(url).hostname.split('.')[0]}-auth-token`, session });
    await page.goto(`/canvas?id=${canvasId}`);
    const board = page.getByTestId('design-node-preview');
    await expect(board).toBeVisible();
    const before = (await board.boundingBox())!;
    await page.mouse.move(before.x + 130, before.y + 200);
    await page.mouse.down();
    await page.mouse.move(before.x + 230, before.y + 220, { steps: 15 });
    await expect.poll(async () => Math.round((await board.boundingBox())!.x - before.x)).toBe(100);
    await page.mouse.up();
    const read = async () => (await (await request.get(`${server}/api/canvases/${canvasId}`, { headers })).json()).canvas;
    await expect.poll(async () => (await read()).content.elements.find((e: any) => e.id === 'test-board').x).toBe(200);
    await expect.poll(async () => Math.round((await board.boundingBox())!.x - before.x)).toBe(100);
    await expect.poll(async () => Math.round((await board.boundingBox())!.y - before.y)).toBe(20);
    const saved = (await read()).content.elements.find((e: any) => e.id === 'test-board');
    expect(saved).toMatchObject({ strokeColor: '#d4d4d4', opacity: 100, strokeWidth: 1 });
    await expect(page.getByTestId('design-node-outline')).toHaveCount(0);
    const dragged = (await board.boundingBox())!;
    await page.mouse.move(dragged.x + dragged.width + 4, dragged.y + dragged.height + 4);
    await page.mouse.down();
    await page.mouse.move(dragged.x + dragged.width + 84, dragged.y + dragged.height + 44, { steps: 10 });
    await page.mouse.up();
    await expect.poll(async () => (await board.boundingBox())!.width).toBeGreaterThan(dragged.width + 50);
    await expect.poll(async () => {
      const latest = (await read()).content.elements.find((e: any) => e.id === 'test-board');
      const visual = (await board.boundingBox())!;
      return Math.abs(visual.width - latest.width) < 1 && Math.abs(visual.height - latest.height) < 1;
    }).toBe(true);
    await page.screenshot({ path: info.outputPath('dragged-board.png') });
    const resized = (await board.boundingBox())!;
    const hint = board.getByTestId('design-node-placeholder');
    const normalHint = (await hint.boundingBox())!;
    await page.mouse.move(resized.x + resized.width + 4, resized.y + resized.height + 4);
    await page.mouse.down();
    await page.mouse.move(resized.x + 44, resized.y + 104, { steps: 15 });
    await page.mouse.up();
    await expect.poll(async () => (await board.boundingBox())!.width).toBeLessThan(60);
    const smallBoard = (await board.boundingBox())!;
    const smallHint = (await hint.boundingBox())!;
    expect(smallHint.width).toBeLessThan(normalHint.width / 2);
    expect(smallHint.x).toBeGreaterThanOrEqual(smallBoard.x);
    expect(smallHint.y).toBeGreaterThanOrEqual(smallBoard.y);
    expect(smallHint.x + smallHint.width).toBeLessThanOrEqual(smallBoard.x + smallBoard.width);
    expect(smallHint.y + smallHint.height).toBeLessThanOrEqual(smallBoard.y + smallBoard.height);
    await expect(hint).toHaveCSS('white-space', 'nowrap');
    await page.screenshot({ path: info.outputPath('small-board-placeholder.png') });
    console.log(JSON.stringify({ canvasId, before, after: await board.boundingBox() }));
  } finally { await auth.auth.signOut({ scope: 'local' }); }
});
