-- Durable, per-API-instance realtime fanout. PostgreSQL polling and consumer
-- cursors are the delivery source of truth.

CREATE TABLE IF NOT EXISTS public.realtime_event_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL CHECK (
    event_type IN ('design.sync', 'workspace.membership.changed')
  ),
  aggregate_id uuid NOT NULL,
  -- Deliberately no FK: a workspace cascade must never be blocked by a member
  -- delete trigger, and its final revocation event may outlive the aggregate.
  workspace_id uuid NOT NULL,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS realtime_event_log_workspace_idx
  ON public.realtime_event_log(workspace_id, id);

CREATE TABLE IF NOT EXISTS public.realtime_event_consumers (
  consumer_id uuid PRIMARY KEY,
  last_event_id bigint NOT NULL DEFAULT 0 CHECK (last_event_id >= 0),
  registered_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.realtime_event_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.realtime_event_consumers ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.realtime_event_log,
  public.realtime_event_consumers FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.realtime_event_log_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.realtime_event_log,
  public.realtime_event_consumers TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.realtime_event_log_id_seq
  TO service_role;

-- This transaction-scoped lock establishes commit order for event IDs. Without
-- it, txn A can allocate id=1 and commit after txn B/id=2, allowing a consumer
-- cursor to advance to 2 while 1 is still invisible. Registration takes the
-- same lock before sampling the tail, closing its startup race as well.
CREATE OR REPLACE FUNCTION private.loomic_realtime_append_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  event_payload jsonb;
  event_workspace_id uuid;
  event_aggregate_id uuid;
  event_name text;
BEGIN
  PERFORM pg_catalog.pg_advisory_xact_lock(589855969625973);

  IF TG_TABLE_NAME = 'design_event_outbox' THEN
    IF NEW.event_type <> 'design.sync' THEN
      RETURN NEW;
    END IF;
    event_name := 'design.sync';
    event_aggregate_id := NEW.design_id;
    event_workspace_id := NEW.workspace_id;
    event_payload := NEW.payload;
  ELSIF TG_TABLE_NAME = 'workspace_members' THEN
    event_name := 'workspace.membership.changed';
    event_aggregate_id := OLD.workspace_id;
    event_workspace_id := OLD.workspace_id;
    event_payload := jsonb_build_object(
      'type', 'workspace.membership.changed',
      'workspaceId', OLD.workspace_id,
      'userId', OLD.user_id,
      'change', CASE WHEN TG_OP = 'DELETE' THEN 'removed' ELSE 'role_changed' END,
      'previousRole', OLD.role,
      'role', CASE WHEN TG_OP = 'UPDATE' THEN NEW.role ELSE NULL END
    );
  ELSE
    RAISE EXCEPTION USING ERRCODE = '55000',
      MESSAGE = 'realtime_event_source_invalid';
  END IF;

  INSERT INTO public.realtime_event_log(
    event_type, aggregate_id, workspace_id, payload
  ) VALUES (
    event_name, event_aggregate_id, event_workspace_id, event_payload
  );
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS design_event_realtime_fanout
  ON public.design_event_outbox;
CREATE TRIGGER design_event_realtime_fanout
AFTER INSERT ON public.design_event_outbox
FOR EACH ROW EXECUTE FUNCTION private.loomic_realtime_append_event();

DROP TRIGGER IF EXISTS workspace_membership_realtime_fanout
  ON public.workspace_members;
DROP TRIGGER IF EXISTS workspace_membership_delete_realtime_fanout
  ON public.workspace_members;
DROP TRIGGER IF EXISTS workspace_membership_role_realtime_fanout
  ON public.workspace_members;
CREATE TRIGGER workspace_membership_delete_realtime_fanout
AFTER DELETE ON public.workspace_members
FOR EACH ROW
EXECUTE FUNCTION private.loomic_realtime_append_event();
CREATE TRIGGER workspace_membership_role_realtime_fanout
AFTER UPDATE OF role ON public.workspace_members
FOR EACH ROW
WHEN (OLD.role IS DISTINCT FROM NEW.role)
EXECUTE FUNCTION private.loomic_realtime_append_event();

CREATE OR REPLACE FUNCTION public.loomic_realtime_consumer_register(
  p_consumer_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  tail_id bigint;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'service_role_required';
  END IF;
  IF p_consumer_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'consumer_id_required';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(589855969625973);
  SELECT COALESCE(max(e.id), 0) INTO tail_id
  FROM public.realtime_event_log e;
  INSERT INTO public.realtime_event_consumers(
    consumer_id, last_event_id, registered_at, last_seen_at
  ) VALUES (p_consumer_id, tail_id, now(), now())
  ON CONFLICT (consumer_id) DO UPDATE
    SET last_seen_at = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.loomic_realtime_consumer_poll(
  p_consumer_id uuid,
  p_limit integer DEFAULT 25
)
RETURNS TABLE (
  event_id text,
  event_type text,
  aggregate_id uuid,
  workspace_id uuid,
  payload jsonb,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  cursor_id bigint;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'service_role_required';
  END IF;
  IF p_consumer_id IS NULL OR p_limit IS NULL OR p_limit < 1 OR p_limit > 100 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'consumer_poll_invalid';
  END IF;

  UPDATE public.realtime_event_consumers c
  SET last_seen_at = now()
  WHERE c.consumer_id = p_consumer_id
  RETURNING c.last_event_id INTO cursor_id;
  IF cursor_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'consumer_not_registered';
  END IF;

  RETURN QUERY
  SELECT e.id::text, e.event_type, e.aggregate_id, e.workspace_id,
    e.payload, e.created_at
  FROM public.realtime_event_log e
  WHERE e.id > cursor_id
  ORDER BY e.id
  LIMIT p_limit;
END;
$$;

CREATE OR REPLACE FUNCTION public.loomic_realtime_consumer_ack(
  p_consumer_id uuid,
  p_event_id bigint
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  affected_rows integer;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'service_role_required';
  END IF;
  IF p_consumer_id IS NULL OR p_event_id IS NULL OR p_event_id < 1 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'consumer_ack_invalid';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.realtime_event_log e WHERE e.id = p_event_id) THEN
    RETURN false;
  END IF;

  UPDATE public.realtime_event_consumers c
  SET last_event_id = p_event_id, last_seen_at = now()
  WHERE c.consumer_id = p_consumer_id
    AND c.last_event_id < p_event_id;
  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  RETURN affected_rows > 0;
END;
$$;

CREATE OR REPLACE FUNCTION public.loomic_realtime_consumer_unregister(
  p_consumer_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'service_role_required';
  END IF;
  DELETE FROM public.realtime_event_consumers c
  WHERE c.consumer_id = p_consumer_id;
END;
$$;

-- Equivalent to the current canvases_select_member RLS path
-- (canvas -> project -> workspace membership), without loading canvas content.
CREATE OR REPLACE FUNCTION public.loomic_realtime_canvas_authorized(
  p_user_id uuid,
  p_canvas_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'service_role_required';
  END IF;
  IF p_user_id IS NULL OR p_canvas_id IS NULL THEN
    RETURN false;
  END IF;
  RETURN EXISTS (
    SELECT 1
    FROM public.canvases c
    JOIN public.projects p ON p.id = c.project_id
    JOIN public.workspace_members m ON m.workspace_id = p.workspace_id
    WHERE c.id = p_canvas_id AND m.user_id = p_user_id
  );
END;
$$;

REVOKE ALL ON FUNCTION private.loomic_realtime_append_event()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.loomic_realtime_consumer_register(uuid),
  public.loomic_realtime_consumer_poll(uuid, integer),
  public.loomic_realtime_consumer_ack(uuid, bigint),
  public.loomic_realtime_consumer_unregister(uuid),
  public.loomic_realtime_canvas_authorized(uuid, uuid)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.loomic_realtime_consumer_register(uuid),
  public.loomic_realtime_consumer_poll(uuid, integer),
  public.loomic_realtime_consumer_ack(uuid, bigint),
  public.loomic_realtime_consumer_unregister(uuid),
  public.loomic_realtime_canvas_authorized(uuid, uuid)
  TO service_role;
